[general]
# Directories to search for templates, relative to the crate root.
dirs = [
    "src/render_passes/shared/shader",
    "src/render_passes/geometry/shader",
    "src/render_passes/light_culling/shader",
    "src/render_passes/material_opaque/shader",
    "src/render_passes/material_transparent/shader",
    "src/render_passes/display/shader",
    "src/render_passes/composite/shader",
    "src/picker/shader",
]
# Unless you add a `-` in a block, whitespace characters won't be trimmed.
whitespace = "preserve"

[[escaper]]
path = "askama::filters::Text"
extensions = ["wgsl"]
